; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:stm8s208s6]
platform = ststm8
board = stm8s208s6
framework = spl
; Use ST-Link for upload by default (adjust `upload_port` if needed)
upload_protocol = stlinkv2
; Uncomment and set upload_port if your programmer requires it
; upload_port = USB
; Include framework headers and project headers
build_flags =
    -I include
    -I ${PROJECT_PACKAGES_DIR}/framework-ststm8spl/Libraries/STM8S_StdPeriph_Driver/inc
extra_scripts = post:extra_script.py